name: example

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    - run: npm install
    - run: npx playwright install
    - run: npm test
  
    - uses: actions/upload-artifact@master
      if: always()
      with:
        name: allure-results
        path: allure-results
        retention-days: 20
        
    - name: Get Allure history
      uses: actions/checkout@v3
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages
    
    - name: Test marketplace action
      uses: simple-elf/allure-report-action@master
      if: always()
      id: allure-report
      with:
        allure_results: allure-results
        gh_pages: gh-pages
        allure_report: allure-report
        allure_history: allure-history
        keep_reports: 20

    - name: Deploy report to Github Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: allure-history

    - name: Post the link to the report
      if: always()
      uses: Sibz/github-status-action@v1
      with: 
        authToken: ${{ secrets.GITHUB_TOKEN }}
        context: 'Test report'
        state: 'success'
        sha: ${{ github.event.pull_request.head.sha || github.sha }}
        target_url: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/${{ github.run_number }} 